# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 8
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/onedrive/54/54.cache/wt [current_project]
set_property parent.project_path D:/onedrive/54/54.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/onedrive/54/54.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet d:/onedrive/54/54.srcs/sources_1/ip/mult/mult.xci
set_property is_locked true [get_files d:/onedrive/54/54.srcs/sources_1/ip/mult/mult.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir D:/onedrive/54/54.runs/mult_synth_1 -new_name mult -ip [get_ips mult]]

if { $cached_ip eq {} } {

synth_design -top mult -part xc7a100tcsg324-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix mult_ mult.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ mult_stub.v
 lappend ipCachedFiles mult_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ mult_stub.vhdl
 lappend ipCachedFiles mult_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ mult_sim_netlist.v
 lappend ipCachedFiles mult_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ mult_sim_netlist.vhdl
 lappend ipCachedFiles mult_sim_netlist.vhdl

 config_ip_cache -add -dcp mult.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips mult]
}

rename_ref -prefix_all mult_

write_checkpoint -force -noxdef mult.dcp

catch { report_utilization -file mult_utilization_synth.rpt -pb mult_utilization_synth.pb }

if { [catch {
  file copy -force D:/onedrive/54/54.runs/mult_synth_1/mult.dcp d:/onedrive/54/54.srcs/sources_1/ip/mult/mult.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force D:/onedrive/54/54.runs/mult_synth_1/mult.dcp d:/onedrive/54/54.srcs/sources_1/ip/mult/mult.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force D:/onedrive/54/54.runs/mult_synth_1/mult_stub.v d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/onedrive/54/54.runs/mult_synth_1/mult_stub.vhdl d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/onedrive/54/54.runs/mult_synth_1/mult_sim_netlist.v d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/onedrive/54/54.runs/mult_synth_1/mult_sim_netlist.vhdl d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir D:/onedrive/54/54.ip_user_files/ip/mult]} {
  catch { 
    file copy -force d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_stub.v D:/onedrive/54/54.ip_user_files/ip/mult
  }
}

if {[file isdir D:/onedrive/54/54.ip_user_files/ip/mult]} {
  catch { 
    file copy -force d:/onedrive/54/54.srcs/sources_1/ip/mult/mult_stub.vhdl D:/onedrive/54/54.ip_user_files/ip/mult
  }
}
