# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/onedrive/54/54.srcs/sources_1/ip/ip_ram_initial/ip_ram_initial.xci
# IP: The module: 'ip_ram_initial' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/onedrive/54/54.srcs/sources_1/ip/ip_ram_initial/ip_ram_initial_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_ram_initial'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/onedrive/54/54.srcs/sources_1/ip/ip_ram_initial/ip_ram_initial.xci
# IP: The module: 'ip_ram_initial' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/onedrive/54/54.srcs/sources_1/ip/ip_ram_initial/ip_ram_initial_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_ram_initial'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
